# .travis.yml
language: node_js
node_js:
  - "0.10"
services:
  - mongodb  # required for good code coverage
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
after_success: 
  - MOCKSOCK=true
  - npm run coverage
  - cat coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js
