module.exports = {
  version: '0.1.7',
  ts: 'Sun Aug 09 2015 13:23:43 GMT-0700 (MST)'
};
// Note: This file is automatically generated when building mmeddle.js.
// Changes made in this file will be overwritten.
