module.exports = {
  version: '0.1.7',
  ts: 'Sat Aug 08 2015 22:44:09 GMT-0700 (MST)'
};
// Note: This file is automatically generated when building mmeddle.js.
// Changes made in this file will be overwritten.
