module.exports = {
  version: '0.1.5',
  ts: 'Sun Aug 02 2015 20:59:37 GMT-0700 (MST)'
};
// Note: This file is automatically generated when building mmeddle.js.
// Changes made in this file will be overwritten.
